# Generated by Django 4.1.4 on 2023-01-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_organization_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="tasks.organization",
            ),
        ),
    ]
