# Generated by Django 4.1.4 on 2022-12-26 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assignment_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
