# Generated by Django 4.1.4 on 2023-01-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="login",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
