# Generated by Django 4.1.4 on 2023-01-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_organization_login"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Milestone",
        ),
    ]
