# Generated by Django 4.1.4 on 2023-01-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_rename_task_milestone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daytask",
            name="priority",
            field=models.CharField(
                choices=[("L", "LOW"), ("H", "HIGH")], default="L", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="daytask",
            name="status",
            field=models.CharField(
                choices=[
                    ("OH", "ON HOLD"),
                    ("NS", "NOT STARTED"),
                    ("IP", "IN PROGRESS"),
                    ("C", "COMPLETE"),
                ],
                default="NS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones_assignments",
                to="tasks.member",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones_authored",
                to="tasks.member",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="priority",
            field=models.CharField(
                choices=[("L", "LOW"), ("H", "HIGH")], default="L", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_milestones",
                to="tasks.project",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("OH", "ON HOLD"),
                    ("NS", "NOT STARTED"),
                    ("IP", "IN PROGRESS"),
                    ("C", "COMPLETE"),
                ],
                default="NS",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("L", "LOW"), ("H", "HIGH")], default="L", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("OH", "ON HOLD"),
                    ("NS", "NOT STARTED"),
                    ("IP", "IN PROGRESS"),
                    ("C", "COMPLETE"),
                ],
                default="NS",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MilestoneTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OH", "ON HOLD"),
                            ("NS", "NOT STARTED"),
                            ("IP", "IN PROGRESS"),
                            ("C", "COMPLETE"),
                        ],
                        default="NS",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("L", "LOW"), ("H", "HIGH")],
                        default="L",
                        max_length=10,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_tasks",
                        to="tasks.milestone",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
