# Generated by Django 4.1.4 on 2023-01-15 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_remove_milestonetask_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milestonetask",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="tasks.milestone",
            ),
        ),
    ]
